### ISSUE TITLE
name session error

### ISSUE THREAD

**Issue by luigifaticoso** [uluQulu/InstaPy-with-QS#1]
## Current Behavior
```
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    multi_logs=True)
  File "/Users/luigicali/InstaPy-with-QS/instapy/instapy.py", line 110, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/luigicali/InstaPy-with-QS/instapy/unfollow_util.py", line 916, in load_follow_restriction
    return json.load(followResFile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 30104 (char 30103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart.py", line 96, in <module>
    session.end()
```
It just happened for no apparent reason, i'm trying to fix it

**Comment by luigifaticoso** [comment]
That's kinda strange, there was a new update of chrome and now it is displaying this:
```
INFO [None]  Session started - 2018-02-18 11:26:06
Cookie file not found, creating cookie...
INFO [None]  Session ended - 2018-02-18 11:26:13
INFO [None]  --------------------


Traceback (most recent call last):
  File "quickstart.py", line 12, in <module>
    session.login()
  File "/Users/luigicali/InstaPy-with-QS/instapy/instapy.py", line 280, in login
    self.bypass_suspicious_attempt):
  File "/Users/luigicali/InstaPy-with-QS/instapy/login_util.py", line 130, in login_user
    click().send_keys(username).perform()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/action_chains.py", line 74, in perform
    action()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/action_chains.py", line 267, in <lambda>
    Command.SEND_KEYS_TO_ACTIVE_ELEMENT, {'value': keys_to_typing(keys_to_send)}))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium-2.53.6-py3.6.egg/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
```

**Comment by luigifaticoso** [comment]
It works with the version from Tim, i'm trying to nuke everything and reclone

**Comment by uluQulu** [comment]
@luigifaticoso 
in **logs** folder
1. **Try** to copy `followRestriction.json` to main repo's **log** folder and if it works there
2. **remove** `yourusername_cookie.pkl`
and try again

**Comment by luigifaticoso** [comment]
```
  File "cali.py", line 17, in <module>
    multi_logs=True,)
  File "/Users/luigicali/InstaPy-with-QS/instapy/instapy.py", line 110, in __init__
    self.follow_restrict = load_follow_restriction(self.logfolder)
  File "/Users/luigicali/InstaPy-with-QS/instapy/unfollow_util.py", line 916, in load_follow_restriction
    return json.load(followResFile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 30104 (char 30103)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cali.py", line 84, in <module>
    session.end()
NameError: name 'session' is not defined
```
it worked by deleting all my **username log folder**

**Comment by uluQulu** [comment]
I think it happened cause of a failure during writing the `json` file to be incomplete
_but you would backup data of useful files such as `blacklist.csv`, `username_followedPool.csv`, and `general.log` and add to the newly opened log files without a problem..._
